'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Pen_and_Paper_v2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property A_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property A_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property A_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property A_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property A_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property A_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property A_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property A_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property A_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property A_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property B_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property B_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property B_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property B_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property B_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property B_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property B_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property B_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property B_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property B_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property C_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property C_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property C_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property C_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property C_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property C_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property C_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property C_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property C_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property C_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property D_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property D_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property D_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property D_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property D_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property D_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property D_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property D_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property D_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property D_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property E_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property E_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property E_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property E_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property E_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property E_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property E_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property E_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property E_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property E_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property F_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property F_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property F_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property F_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property F_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property F_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property F_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property F_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property F_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property F_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property G_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property G_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property G_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property G_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property G_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property G_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property G_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property G_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property G_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property G_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property H_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property H_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property H_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property H_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property H_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property H_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property H_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property H_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property H_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property H_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property J_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property J_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property J_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property J_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property J_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property J_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property J_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property J_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property J_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property J_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property lupe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lupe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die A1_A1=True
        '''A1_A2=True
        '''A1_A3=True
        '''A1_A4=True
        '''A1_A5=True
        '''A1_B1=True
        '''A1_B2=True
        '''A1_B3=True
        '''A1_B4=True
        '''A1_B5=True
        '''A1_C1=True
        '''A1_C2=True
        '''A1_C3=True
        '''A1_C4=True
        '''A1_C5=True
        '''A1_D1=True
        '''A1_D2=True
        '''A1_D3=True
        '''A1_D4=True
        '''A1_D5=True
        '''A1_E1=True
        '''A1_E2=True
        '''A1_E3=True
        '''A1_E4=True
        '''A1_E5=True
        '''A2_A1=True
        '''A2_A2=True
        '''A2_A3=True
        '''A2_A4=True
        '''A2_A5=True
        '''A2_B1=True
        '''A2_B2=True
        '''A2_B3=True
        '''A2_B4=True
        '''A2_B5=True
        '''A2_C1=True
        '''A2_C2=True
        '''A2_C3=True
        '''A2_C4=True
        '''A2_C5=True
        '''A2_D1=True
        '''A2_D2=True
        '''A2_D3=Tr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property Player() As String
            Get
                Return ResourceManager.GetString("Player", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Weiß() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weiß", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property zuruck_pfeil_links_symbol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zuruck_pfeil_links_symbol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
